apiVersion: v2
name: scan-exporter-chart
description: A Helm chart to deploy scan-exporter in Kubernetes
type: application
version: 1.0.0
appVersion: "0.6.1"
home: https://github.com/devops-works/scan-exporter
sources:
  - https://github.com/devops-works/scan-exporter
dependencies:
    - name: redis
      version: 11.2.1
      repository: https://charts.bitnami.com/bitnami
maintainers:
- name: devopsworks
  email: support@devops.works
- name: ezekiel
  email: hugo@devops.works
