scanexporter:
    name: scan-exporter
    replicaCount: 1
    liveness:
        initialDelay: 20
        period: 3
        path: /health
    container:
        image: devopsworks/scan-exporter:0.6.3
        port: 2112

redis:
    name: redis
    usePassword: false
    replicaCount: 1
    db: 0
    container:
        image: redis:latest
        port: 6379

nameOverride: ""
fullnameOverride: ""

podMonitor: 
    enabled: false
    path: /metrics

targets: |-
         targets:
             - name: "app1"
               ip: "198.51.100.1"
               workers: 750
               tcp:
                 period: "10s"
                 range: "reserved"
                 expected: "53"
             - name: "app2"
               ip: "198.51.100.2"
               workers: 1000
               tcp:
                 period: "1m"
                 range: "all"
                 expected: "22,443"
               icmp:
                 period: "30s"
