scanexporter:
    name: scan-exporter
    replicaCount: 1
    liveness:
        period: 3
        path: /health
    container:
        image: devopsworks/scan-exporter:0.0.3
        port: 2112
    secrets: regcred
    resources:
        limits:
            cpu: 100m
            memory: 64Mi
        requests:
            cpu: 100m
            memory: 64Mi

redis:
    name: redis
    usePassword: false
    replicaCount: 1
    db: 0
    container:
        image: redis:latest
        port: 6379

nameOverride: ""
fullnameOverride: ""

podMonitor: 
    enabled: false
    path: /metrics

targets: |-
        targets:       
            - name: "app1"
              ip: "10.11.12.13"
              workers: 750
              tcp:
                period: "10s"
                range: "reserved"
                expected: "53"

            - name: "app2"
              ip: "110.111.112.113"
              workers: 1000
              tcp:
                period: "1m"
                range: "all"
                expected: "22,443"
              icmp:
                period: "30s"