scanexporter:
    name: scan-exporter
    replicaCount: 1
    liveness:
        initialDelay: 20
        period: 3
        path: /health
    container:
        image: devopsworks/scan-exporter:2.0.0
        imagePullPolicy: Always
        port: 2112
    resources:
        requests:
            memory: "100Mi"
            cpu: "200m"
        limits:
            memory: "150Mi"
            cpu: "375m"

nameOverride: ""
fullnameOverride: ""

podMonitor: 
    enabled: false
    path: /metrics

targets: |-
         timeout: 2
         limit: 1024
         targets:
             - name: "app1"
               ip: "198.51.100.1"
               tcp:
                 period: "10s"
                 range: "reserved"
                 expected: "53"
             - name: "app2"
               ip: "198.51.100.2"
               tcp:
                 period: "1m"
                 range: "all"
                 expected: "22,443"
               icmp:
                 period: "30s"
