apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backupkrane.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "backupkrane.name" . }}
    helm.sh/chart: {{ include "backupkrane.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    devops.works/customer: {{ .Values.customer }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  BK_BUCKETSOURCE_CREDENTIALS: {{ .Values.bucketSource.credentials | b64enc }}
  BK_BUCKETSOURCE_TYPE: {{ .Values.bucketSource.type | b64enc }}
  BK_BUCKETSOURCE_URL: {{ .Values.bucketSource.url | b64enc }}
  BK_BUCKETDESTINATION_URL: {{ .Values.bucketDestination.url | b64enc }}
  BK_BUCKETDESTINATION_TYPE: {{ .Values.bucketDestination.type | b64enc }}
  BK_BUCKETDESTINATION_CREDENTIALS: {{ .Values.bucketDestination.credentials | b64enc }}
  BK_GPG_PRIVATE_KEY: {{ .Values.gpgPrivateKey | b64enc }}
  BK_TEST_FILE: {{ .Values.test_file_path }}{{ .Values.test_file }}